[build]
base = "./"
command = "npm run build"
publish = "_site"

[functions]
directory = "serverless"
included_files = [
  "./node_modules/sciolyff/**/*",
  "./node_modules/commander/**/*",
  "./node_modules/fetch-retry/**/*",
  "./node_modules/js-yaml/**/*",
  "./node_modules/neat-csv/**/*",
  "./node_modules/node-fetch/**/*",
  "./node_modules/yup/**/*",
  "./node_modules/argparse/**/*",
  "./node_modules/csv-parser/**/*",
  "./node_modules/minimist/**/*",
  "./node_modules/get-stream/**/*",
  "./node_modules/data-uri-to-buffer/**/*",
  "./node_modules/fetch-blob/**/*",
  "./node_modules/node-domexception/**/*",
  "./node_modules/web-streams-polyfill/**/*",
  "./node_modules/formdata-polyfill/**/*",
  "./node_modules/@babel/runtime/**/*",
  "./node_modules/regenerator-runtime/**/*",
  "./node_modules/@types/lodash/**/*",
  "./node_modules/lodash/**/*",
  "./node_modules/lodash-es/**/*",
  "./node_modules/nanoclone/**/*",
  "./node_modules/property-expr/**/*",
  "./node_modules/toposort/**/*"
]

[[redirects]]
from = "/results/superscore/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/"
status = 302
to = "/results"

[[redirects]]
from = "/input-template"
to = "https://docs.google.com/spreadsheets/d/1thaKvnlrv1j0CLbsZUvpjalGUbX0Q93TAeEAFSvjv8M/copy"

[[redirects]]
from = "/duostac"
to = "https://docs.google.com/forms/d/e/1FAIpQLSeYZ8YaTm9t-A80xewnUtIZ_NqIUZHDrFf1UsGon-DbEH5uQQ/viewform?usp=sf_link"
