[build]
base = "./"
command = "npm run build"
publish = "_site"

[functions]
directory = "serverless"
node_bundler = "esbuild"

[[redirects]]
from = "/results/:filename/"
to = "/.netlify/functions/odb"
status = 200
force = true
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/"
to = "/results"
status = 302

[[redirects]]
from = "/input-template"
to = "https://docs.google.com/spreadsheets/d/1thaKvnlrv1j0CLbsZUvpjalGUbX0Q93TAeEAFSvjv8M/copy"

[[redirects]]
from = "/duostac"
to = "https://docs.google.com/forms/d/e/1FAIpQLSeYZ8YaTm9t-A80xewnUtIZ_NqIUZHDrFf1UsGon-DbEH5uQQ/viewform?usp=sf_link"
