[build]
base = "./"
command = "npm run build"
publish = "_site"

[functions]
directory = "serverless"
included_files = [
  "./node_modules/sciolyff/**/*",
  "./node_modules/@vanillaes/csv/**/*",
  "./node_modules/node-fetch/**/*",
  "./node_modules/data-uri-to-buffer/**/*",
  "./node_modules/fetch-blob/**/*",
  "./node_modules/node-domexception/**/*",
  "./node_modules/web-streams-polyfill/**/*",
  "./node_modules/formdata-polyfill/**/*"
]

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ "_site/images", "_site/data" ]

[[redirects]]
from = "/"
status = 302
to = "/results/"

[[redirects]]
from = "/input-template"
to = "https://docs.google.com/spreadsheets/d/1thaKvnlrv1j0CLbsZUvpjalGUbX0Q93TAeEAFSvjv8M/copy"

[[redirects]]
from = "/duostac"
to = "https://docs.google.com/forms/d/e/1FAIpQLSeYZ8YaTm9t-A80xewnUtIZ_NqIUZHDrFf1UsGon-DbEH5uQQ/viewform?usp=sf_link"

[[redirects]]
from = "/results/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/csv/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/superscore/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/preview/meta/"
to = "/.netlify/functions/dynamicpost"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamicpost"

[[redirects]]
from = "/preview/render/"
to = "/.netlify/functions/dynamicpost"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamicpost"

[[redirects]]
from = "/preview/validate/"
to = "/.netlify/functions/dynamicpost"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamicpost"
