[build]
base = "./"
command = "npm run build"
publish = "_site"

[functions]
directory = "serverless"
node_bundler = "zisi"

  [functions.dynamicpost]
  included_files = [
  "./serverless/dynamicpost/**/*",
  "./node_modules/sciolyff/**/*",
  "./node_modules/@vanillaes/csv/**/*",
  "./node_modules/node-fetch/**/*",
  "./node_modules/data-uri-to-buffer/**/*",
  "./node_modules/fetch-blob/**/*",
  "./node_modules/node-domexception/**/*",
  "./node_modules/web-streams-polyfill/**/*",
  "./node_modules/formdata-polyfill/**/*"
]

  [functions.odb]
  included_files = [
  "./serverless/odb/**/*",
  "./node_modules/sciolyff/**/*",
  "./node_modules/@vanillaes/csv/**/*",
  "./node_modules/node-fetch/**/*",
  "./node_modules/data-uri-to-buffer/**/*",
  "./node_modules/fetch-blob/**/*",
  "./node_modules/node-domexception/**/*",
  "./node_modules/web-streams-polyfill/**/*",
  "./node_modules/formdata-polyfill/**/*"
]

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ "_site/images", "_site/data" ]

[[redirects]]
from = "/"
status = 302
to = "/results/"

[[redirects]]
from = "/input-template"
to = "https://docs.google.com/spreadsheets/d/1vKw-WWYtMsNM5gqd9Fea4teo3DXbpg1WVqxIerwnddQ/copy"

[[redirects]]
from = "/tournament-director"
to = "https://docs.google.com/spreadsheets/d/1BU2NNoA7YYS2cHBEK3jMZfT6sEXP8oi1sY95Wbe7ks4/copy"

[[redirects]]
from = "/event-supervisor"
to = "https://docs.google.com/spreadsheets/d/1_kJcZbW4YlD96YHDRFoLXcFjVopVUhX0CoMvw5GnlJM/copy"

[[redirects]]
from = "ucsdcubing"
to = "https://jonatanklosko.github.io/rankings/#/rankings/show?name=UCSD&wcaids=2013HELM02%2C2013SING12%2013ZHEN11%2C2014MUNJ02%2C2014TANG03%2C2015GOVI01%2C2015LEHM01%2C2016MECK01%2C2017LIWI03%2C2022LURU01%2C2022TAOS01%2C2022ZHAN52%2C2023CHAN15%2C2023GROS06%2C2023NGUY04%2C2023POTL01%2C2023SEHG03%2C2023WANG32%2C2023XINY01%2C2023ZHAO08%2C2024MATS04%2C2011NATH02%2022LIUJ09%2017TSAI05"
[[redirects]]
from = "/screenshot/*"
to = "/.netlify/builders/screenshot"
status = 200
force = true

[[redirects]]
from = "/results/2023-02-25_nCA_barsoregional_b/"
to = "/results/2023-02-25_nCA_bay_area_regional_b/"
status = 301

[[redirects]]
from = "/results/2023-02-25_nCA_barsoregional_c/"
to = "/results/2023-02-25_nCA_bay_area_regional_c/"
status = 301

[[redirects]]
from = "/results/2023-02-25_nca_barsoregional_b/"
to = "/results/2023-02-25_nCA_bay_area_regional_b/"
status = 301

[[redirects]]
from = "/results/2023-02-25_nca_barsoregional_c/"
to = "/results/2023-02-25_nCA_bay_area_regional_c/"
status = 301

[[redirects]]
from = "/results/2023-03-11_nCA_santa_clara_county_regional_c/"
to = "/results/2023-03-11_nCA_santa_clara_regional_c/"
status = 301

[[redirects]]
from = "/results/2022-03-19_PA_southeast_pa_regional_c/"
to = "/results/2022-03-19_PA_southeastern_pa_regional_c/"
status = 301

[[redirects]]
from = "/results/2021-03-16_PA_sepa_regional_c/"
to = "/results/2021-03-16_PA_southeastern_pa_regional_c/"
status = 301

[[redirects]]
from = "/results/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/csv/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/histo/:filename/:event/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/superscore/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/preview/meta/"
to = "/.netlify/functions/dynamicpost"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamicpost"

[[redirects]]
from = "/preview/render/"
to = "/.netlify/functions/dynamicpost"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamicpost"

[[redirects]]
from = "/preview/validate/"
to = "/.netlify/functions/dynamicpost"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamicpost"

[[headers]]
for = "/*"

  [headers.values]
  Access-Control-Allow-Origin = "*"
