[build]
base = "./"
command = "npm run build"
publish = "_site"

[functions]
directory = "serverless"
included_files = [
  "./node_modules/sciolyff/**/*",
  "./node_modules/neat-csv/**/*",
  "./node_modules/csv-parser/**/*",
  "./node_modules/minimist/**/*",
  "./node_modules/get-stream/**/*"
]

[[redirects]]
from = "/"
status = 302
to = "/results"

[[redirects]]
from = "/input-template"
to = "https://docs.google.com/spreadsheets/d/1thaKvnlrv1j0CLbsZUvpjalGUbX0Q93TAeEAFSvjv8M/copy"

[[redirects]]
from = "/duostac"
to = "https://docs.google.com/forms/d/e/1FAIpQLSeYZ8YaTm9t-A80xewnUtIZ_NqIUZHDrFf1UsGon-DbEH5uQQ/viewform?usp=sf_link"

[[redirects]]
from = "/results/superscore/preview/"
to = "/preview/"

[[redirects]]
from = "/results/preview/"
to = "/preview/"

[[redirects]]
from = "/data/preview.yaml"
to = "/preview/"

[[redirects]]
from = "/results/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/superscore/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/preview/render/"
to = "/.netlify/builders/dynamicpost"
status = 200
force = false
_generated_by_eleventy_serverless = "dynamicpost"
