[build]
base = "./"
command = "npm run build"
publish = "_site"

[functions]
directory = "serverless"

  [functions.dynamicpost]
  included_files = [
  "./node_modules/sciolyff/**/*",
  "./node_modules/@vanillaes/csv/**/*",
  "./node_modules/node-fetch/**/*",
  "./node_modules/data-uri-to-buffer/**/*",
  "./node_modules/fetch-blob/**/*",
  "./node_modules/node-domexception/**/*",
  "./node_modules/web-streams-polyfill/**/*",
  "./node_modules/formdata-polyfill/**/*"
]

  [functions.odb]
  included_files = [
  "./node_modules/sciolyff/**/*",
  "./node_modules/@vanillaes/csv/**/*",
  "./node_modules/node-fetch/**/*",
  "./node_modules/data-uri-to-buffer/**/*",
  "./node_modules/fetch-blob/**/*",
  "./node_modules/node-domexception/**/*",
  "./node_modules/web-streams-polyfill/**/*",
  "./node_modules/formdata-polyfill/**/*"
]

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ "_site/images", "_site/data" ]

[[redirects]]
from = "/"
status = 302
to = "/results/"

[[redirects]]
from = "/input-template"
to = "https://docs.google.com/spreadsheets/d/1o2sMLBPViqNgCa34P09HWROwAyOU6njWi1T-tisI6DY/copy"

[[redirects]]
from = "/tournament-director"
to = "https://docs.google.com/spreadsheets/d/1BU2NNoA7YYS2cHBEK3jMZfT6sEXP8oi1sY95Wbe7ks4/copy"

[[redirects]]
from = "/event-supervisor"
to = "https://docs.google.com/spreadsheets/d/1_kJcZbW4YlD96YHDRFoLXcFjVopVUhX0CoMvw5GnlJM/copy"

[[redirects]]
from = "/screenshot/*"
to = "/.netlify/builders/screenshot"
status = 200
force = true

[[redirects]]
from = "/results/2023-02-25_nCA_barsoregional_b/"
to = "/results/2023-02-25_nCA_bay_area_regional_b/"
status = 301

[[redirects]]
from = "/results/2023-02-25_nCA_barsoregional_c/"
to = "/results/2023-02-25_nCA_bay_area_regional_c/"
status = 301

[[redirects]]
from = "/results/2023-02-25_nca_barsoregional_b/"
to = "/results/2023-02-25_nCA_bay_area_regional_b/"
status = 301

[[redirects]]
from = "/results/2023-02-25_nca_barsoregional_c/"
to = "/results/2023-02-25_nCA_bay_area_regional_c/"
status = 301

[[redirects]]
from = "/results/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/csv/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/histo/:filename/:event/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/results/superscore/:filename/"
to = "/.netlify/builders/odb"
status = 200
force = false
_generated_by_eleventy_serverless = "odb"

[[redirects]]
from = "/preview/meta/"
to = "/.netlify/functions/dynamicpost"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamicpost"

[[redirects]]
from = "/preview/render/"
to = "/.netlify/functions/dynamicpost"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamicpost"

[[redirects]]
from = "/preview/validate/"
to = "/.netlify/functions/dynamicpost"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamicpost"

[[headers]]
for = "/*"

  [headers.values]
  Access-Control-Allow-Origin = "*"
